# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/position_service.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='proto/position_service.proto',
    package='line_following',
    syntax='proto3',
    serialized_pb=_b(
        '\n\x1cproto/position_service.proto\x12\x0eline_following\"\x1a\n\nClientInfo\x12\x0c\n\x04info\x18\x01 \x01(\t\"\x1a\n\nServerInfo\x12\x0c\n\x04info\x18\x01 \x01(\t\"\x88\x01\n\x08Position\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08in_focus\x18\x02 \x01(\x08\x12\x12\n\nmid_offset\x18\x03 \x01(\x05\x12\x0f\n\x07\x64\x65grees\x18\x04 \x01(\x05\x12\x16\n\x0emid_line_cross\x18\x05 \x01(\x05\x12\r\n\x05width\x18\x06 \x01(\x05\x12\x12\n\nmiddle_inc\x18\x07 \x01(\x05\x32\xa7\x01\n\x0fPositionService\x12J\n\x0eregisterClient\x12\x1a.line_following.ClientInfo\x1a\x1a.line_following.ServerInfo\"\x00\x12H\n\x0cgetPositions\x12\x1a.line_following.ClientInfo\x1a\x18.line_following.Position\"\x00\x30\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_CLIENTINFO = _descriptor.Descriptor(
    name='ClientInfo',
    full_name='line_following.ClientInfo',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='info', full_name='line_following.ClientInfo.info', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=48,
    serialized_end=74,
)

_SERVERINFO = _descriptor.Descriptor(
    name='ServerInfo',
    full_name='line_following.ServerInfo',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='info', full_name='line_following.ServerInfo.info', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=76,
    serialized_end=102,
)

_POSITION = _descriptor.Descriptor(
    name='Position',
    full_name='line_following.Position',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='id', full_name='line_following.Position.id', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='in_focus', full_name='line_following.Position.in_focus', index=1,
            number=2, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='mid_offset', full_name='line_following.Position.mid_offset', index=2,
            number=3, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='degrees', full_name='line_following.Position.degrees', index=3,
            number=4, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='mid_line_cross', full_name='line_following.Position.mid_line_cross', index=4,
            number=5, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='width', full_name='line_following.Position.width', index=5,
            number=6, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='middle_inc', full_name='line_following.Position.middle_inc', index=6,
            number=7, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=105,
    serialized_end=241,
)

DESCRIPTOR.message_types_by_name['ClientInfo'] = _CLIENTINFO
DESCRIPTOR.message_types_by_name['ServerInfo'] = _SERVERINFO
DESCRIPTOR.message_types_by_name['Position'] = _POSITION

ClientInfo = _reflection.GeneratedProtocolMessageType('ClientInfo', (_message.Message,), dict(
    DESCRIPTOR=_CLIENTINFO,
    __module__='proto.position_service_pb2'
    # @@protoc_insertion_point(class_scope:line_following.ClientInfo)
))
_sym_db.RegisterMessage(ClientInfo)

ServerInfo = _reflection.GeneratedProtocolMessageType('ServerInfo', (_message.Message,), dict(
    DESCRIPTOR=_SERVERINFO,
    __module__='proto.position_service_pb2'
    # @@protoc_insertion_point(class_scope:line_following.ServerInfo)
))
_sym_db.RegisterMessage(ServerInfo)

Position = _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), dict(
    DESCRIPTOR=_POSITION,
    __module__='proto.position_service_pb2'
    # @@protoc_insertion_point(class_scope:line_following.Position)
))
_sym_db.RegisterMessage(Position)

try:
    # THESE ELEMENTS WILL BE DEPRECATED.
    # Please use the generated *_pb2_grpc.py files instead.
    import grpc
    from grpc.framework.common import cardinality
    from grpc.framework.interfaces.face import utilities as face_utilities
    from grpc.beta import implementations as beta_implementations
    from grpc.beta import interfaces as beta_interfaces


    class PositionServiceStub(object):

        def __init__(self, channel):
            """Constructor.
      
            Args:
              channel: A grpc.Channel.
            """
            self.registerClient = channel.unary_unary(
                '/line_following.PositionService/registerClient',
                request_serializer=ClientInfo.SerializeToString,
                response_deserializer=ServerInfo.FromString,
            )
            self.getPositions = channel.unary_stream(
                '/line_following.PositionService/getPositions',
                request_serializer=ClientInfo.SerializeToString,
                response_deserializer=Position.FromString,
            )


    class PositionServiceServicer(object):

        def registerClient(self, request, context):
            context.set_code(grpc.StatusCode.UNIMPLEMENTED)
            context.set_details('Method not implemented!')
            raise NotImplementedError('Method not implemented!')

        def getPositions(self, request, context):
            context.set_code(grpc.StatusCode.UNIMPLEMENTED)
            context.set_details('Method not implemented!')
            raise NotImplementedError('Method not implemented!')


    def add_PositionServiceServicer_to_server(servicer, server):
        rpc_method_handlers = {
            'registerClient': grpc.unary_unary_rpc_method_handler(
                servicer.registerClient,
                request_deserializer=ClientInfo.FromString,
                response_serializer=ServerInfo.SerializeToString,
            ),
            'getPositions': grpc.unary_stream_rpc_method_handler(
                servicer.getPositions,
                request_deserializer=ClientInfo.FromString,
                response_serializer=Position.SerializeToString,
            ),
        }
        generic_handler = grpc.method_handlers_generic_handler(
            'line_following.PositionService', rpc_method_handlers)
        server.add_generic_rpc_handlers((generic_handler,))


    class BetaPositionServiceServicer(object):
        """The Beta API is deprecated for 0.15.0 and later.
    
        It is recommended to use the GA API (classes and functions in this
        file not marked beta) for all further purposes. This class was generated
        only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""

        def registerClient(self, request, context):
            context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)

        def getPositions(self, request, context):
            context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


    class BetaPositionServiceStub(object):
        """The Beta API is deprecated for 0.15.0 and later.
    
        It is recommended to use the GA API (classes and functions in this
        file not marked beta) for all further purposes. This class was generated
        only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""

        def registerClient(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
            raise NotImplementedError()

        registerClient.future = None

        def getPositions(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
            raise NotImplementedError()


    def beta_create_PositionService_server(servicer, pool=None, pool_size=None, default_timeout=None,
                                           maximum_timeout=None):
        """The Beta API is deprecated for 0.15.0 and later.
    
        It is recommended to use the GA API (classes and functions in this
        file not marked beta) for all further purposes. This function was
        generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
        request_deserializers = {
            ('line_following.PositionService', 'getPositions'): ClientInfo.FromString,
            ('line_following.PositionService', 'registerClient'): ClientInfo.FromString,
        }
        response_serializers = {
            ('line_following.PositionService', 'getPositions'): Position.SerializeToString,
            ('line_following.PositionService', 'registerClient'): ServerInfo.SerializeToString,
        }
        method_implementations = {
            ('line_following.PositionService', 'getPositions'): face_utilities.unary_stream_inline(
                servicer.getPositions),
            ('line_following.PositionService', 'registerClient'): face_utilities.unary_unary_inline(
                servicer.registerClient),
        }
        server_options = beta_implementations.server_options(request_deserializers=request_deserializers,
                                                             response_serializers=response_serializers,
                                                             thread_pool=pool, thread_pool_size=pool_size,
                                                             default_timeout=default_timeout,
                                                             maximum_timeout=maximum_timeout)
        return beta_implementations.server(method_implementations, options=server_options)


    def beta_create_PositionService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
        """The Beta API is deprecated for 0.15.0 and later.
    
        It is recommended to use the GA API (classes and functions in this
        file not marked beta) for all further purposes. This function was
        generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
        request_serializers = {
            ('line_following.PositionService', 'getPositions'): ClientInfo.SerializeToString,
            ('line_following.PositionService', 'registerClient'): ClientInfo.SerializeToString,
        }
        response_deserializers = {
            ('line_following.PositionService', 'getPositions'): Position.FromString,
            ('line_following.PositionService', 'registerClient'): ServerInfo.FromString,
        }
        cardinalities = {
            'getPositions': cardinality.Cardinality.UNARY_STREAM,
            'registerClient': cardinality.Cardinality.UNARY_UNARY,
        }
        stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer,
                                                         request_serializers=request_serializers,
                                                         response_deserializers=response_deserializers,
                                                         thread_pool=pool, thread_pool_size=pool_size)
        return beta_implementations.dynamic_stub(channel, 'line_following.PositionService', cardinalities,
                                                 options=stub_options)
except ImportError:
    pass
# @@protoc_insertion_point(module_scope)
